"""Carry the writing sweep's thesis copy into data/demo.db (audit item 14b, Operations).

The Trade Log renders thesis prose seeded into demo.db. Seeded prose is insert-only, so
this writes the swept text into the committed book, cell by cell. Where a seed module
holds a cell's text verbatim (the system theses' exit conditions, three SLEEVE_META
fields), the seed carries the same new text. The SPAXX position thesis (23) is left to
tools/migrate_markets_copy.py, which keeps it equal to the Research page's text.

Each UPDATE is keyed on the thesis id and the cell's current text, must change exactly
one row, or the run rolls back; a second run changes nothing. Targets data/demo.db
explicitly and runs from main() only. The personal book is not touched.
"""
import sqlite3
from pathlib import Path

DEMO_DB = Path(__file__).resolve().parent.parent / "data" / "demo.db"

# One literal statement per column, so a scan of the tools for UPDATE statements sees
# each one whole (an f-string hid 15b's from #288's guard).
UPDATES = {
    "macro_view":
        "UPDATE theses SET macro_view = ? WHERE thesis_id = ? AND macro_view = ?",
    "view_summary":
        "UPDATE theses SET view_summary = ? WHERE thesis_id = ? AND view_summary = ?",
    "vehicle_rationale":
        "UPDATE theses SET vehicle_rationale = ? WHERE thesis_id = ? AND vehicle_rationale = ?",
    "exit_conditions":
        "UPDATE theses SET exit_conditions = ? WHERE thesis_id = ? AND exit_conditions = ?",
    "invalidation_conditions":
        "UPDATE theses SET invalidation_conditions = ? WHERE thesis_id = ? "
        "AND invalidation_conditions = ?",
    "expected_return_scenario":
        "UPDATE theses SET expected_return_scenario = ? WHERE thesis_id = ? "
        "AND expected_return_scenario = ?",
}

NEW = {
    "1": {
        "exit_conditions": "Never closes: operational thesis."
    },
    "2": {
        "exit_conditions": "Never closes: operational thesis."
    },
    "3": {
        "macro_view": "Anchor exposure to US large-cap equity: the cap-weighted S&P 500, the most efficient, best-governed, and highest-quality earnings stream in global markets. The 16% weight is deliberately not the largest US sleeve (Quality at 14% comes close), because most US large-cap exposure should express a factor view rather than passive cap weight. Core is the un-opinionated anchor: when the factor tilts go through their inevitable multi-year stretches of underperformance, Core keeps the portfolio in the broad equity rally. Would increase if factor premia compress further or if conviction in the active factor tilts erodes.",
        "view_summary": "Anchor exposure to US large-cap equity: the cap-weighted S&P 500, the most efficient, best-governed, and highest-quality earnings stream in global markets. The 16% weight is deliberately not the largest US sleeve (Quality at 14% comes close), because most US large-cap exposure should express a factor view rather than passive cap weight. Core is the un-opinionated anchor: when the factor tilts go through their inevitable multi-year stretches of underperformance, Core keeps the portfolio in the broad equity rally. Would increase if factor premia compress further or if conviction in the active factor tilts erodes."
    },
    "4": {
        "macro_view": "The largest factor tilt in the portfolio, deliberately. Quality (high ROIC, low leverage, stable earnings) is the only factor that has strengthened since academic publication. It is a structural preference for better businesses, not statistical arbitrage, so it is not arbitraged away. Empirically, quality has delivered equity-like returns with materially lower drawdowns. That matters over a 30+ year compounding window, where avoiding deep drawdowns dominates terminal wealth. 14% expresses high conviction without enough concentration for a factor regime change to severely damage the portfolio. Would reduce if quality screens become dominated by a single sector to the point of losing diversification.",
        "view_summary": "The largest factor tilt in the portfolio, deliberately. Quality (high ROIC, low leverage, stable earnings) is the only factor that has strengthened since academic publication. It is a structural preference for better businesses, not statistical arbitrage, so it is not arbitraged away. Empirically, quality has delivered equity-like returns with materially lower drawdowns. That matters over a 30+ year compounding window, where avoiding deep drawdowns dominates terminal wealth. 14% expresses high conviction without enough concentration for a factor regime change to severely damage the portfolio. Would reduce if quality screens become dominated by a single sector to the point of losing diversification.",
        "expected_return_scenario": "Quality premium of ~1-2% over market annually with materially lower drawdowns; equity-like returns with a smoother compounding path."
    },
    "5": {
        "macro_view": "A smaller, contextual factor bet on growth-versus-value mean reversion. The Russell 1000 Value versus Growth spread is at its deepest valuation gap since 2000. The mean-reversion case is real: over 10-year windows, the historical base rate favors value at these spreads. But value has had several \"this time it'll work\" moments since 2010 that did not deliver, so the position is sized to express the view without betting the portfolio on it. 8% out of the 38% total in US large caps is 21% of US large-cap exposure. Would increase if the spread widens further or if real rates normalize; would reduce if growth's earnings advantage compounds for another 5+ years.",
        "view_summary": "A smaller, contextual factor bet on growth-versus-value mean reversion. The Russell 1000 Value versus Growth spread is at its deepest valuation gap since 2000. The mean-reversion case is real: over 10-year windows, the historical base rate favors value at these spreads. But value has had several \"this time it'll work\" moments since 2010 that did not deliver, so the position is sized to express the view without betting the portfolio on it. 8% out of the 38% total in US large caps is 21% of US large-cap exposure. Would increase if the spread widens further or if real rates normalize; would reduce if growth's earnings advantage compounds for another 5+ years."
    },
    "6": {
        "macro_view": "Size factor exposure, sized modestly because the evidence is the weakest. Small caps have historically earned a ~1-2% premium over large caps, but the premium has been weak since publication and arguably absent for the last 15 years. Small caps offer genuine diversification: they are more domestic-economy-leveraged, more interest-rate-sensitive, and less correlated with mega-cap tech concentration. 7% is enough to matter if the size premium reasserts, especially with valuation discounts to large caps at multi-decade lows, without anchoring the portfolio to a factor with shaky empirical support. Would increase if real rates normalize and small-cap quality screens produce attractive opportunities.",
        "view_summary": "Size factor exposure, sized modestly because the evidence is the weakest. Small caps have historically earned a ~1-2% premium over large caps, but the premium has been weak since publication and arguably absent for the last 15 years. Small caps offer genuine diversification: they are more domestic-economy-leveraged, more interest-rate-sensitive, and less correlated with mega-cap tech concentration. 7% is enough to matter if the size premium reasserts, especially with valuation discounts to large caps at multi-decade lows, without anchoring the portfolio to a factor with shaky empirical support. Would increase if real rates normalize and small-cap quality screens produce attractive opportunities."
    },
    # Theses 7 and 17 described the undivided International Developed sleeve; both are
    # condensed from International Core's SAA rationale, with no claim it lacks
    # (#406 item 4). The fields it has nothing for are cleared.
    "7": {
        "macro_view": "The developed ex-US region, where the international sleeves apply the US book's structure, so their weights follow from choices already made. Its core is the cap-weighted market, held for the reason any core position is held: it is the region without a view. Every tilt in this book is a deviation from a market portfolio, and a deviation is only meaningful if the portfolio it deviates from is also owned.",
        "view_summary": "The developed ex-US region, where the international sleeves apply the US book's structure, so their weights follow from choices already made. Its core is the cap-weighted market, held for the reason any core position is held: it is the region without a view. Every tilt in this book is a deviation from a market portfolio, and a deviation is only meaningful if the portfolio it deviates from is also owned.",
        "exit_conditions": "Would revisit if the US core weight changes, since the core sleeve is defined as the US core's international mirror rather than sized on its own.",
        "invalidation_conditions": None,
        "expected_return_scenario": None
    },
    "8": {
        "macro_view": "A higher-growth, higher-volatility diversifier. EM equities offer demographic tailwinds, structurally cheaper valuations, and growth profiles that developed markets do not have. The 8% weight respects the asymmetric risk: EM has had 50%+ drawdowns several times and includes meaningful country-specific governance risk, China especially. A modest position at attractive valuations is preferred to buying after a rally. Would increase if EM ex-China valuations become exceptionally cheap; would reduce if China governance risk materially worsens or if EM index construction concentrates further into a single country.",
        "view_summary": "A higher-growth, higher-volatility diversifier. EM equities offer demographic tailwinds, structurally cheaper valuations, and growth profiles that developed markets do not have. The 8% weight respects the asymmetric risk: EM has had 50%+ drawdowns several times and includes meaningful country-specific governance risk, China especially. A modest position at attractive valuations is preferred to buying after a rally. Would increase if EM ex-China valuations become exceptionally cheap; would reduce if China governance risk materially worsens or if EM index construction concentrates further into a single country.",
        "exit_conditions": "Would reduce if China governance risk materially worsens or if EM index construction concentrates further into a single country."
    },
    "9": {
        "macro_view": "Duration as recession ballast, sized for an aggressive growth portfolio. Classical 60/40 doctrine assumed Treasuries reliably hedged equity drawdowns; 2022 disproved that under inflationary regimes. But in deflationary or recessionary drawdowns, which remain the more common equity tail risk, intermediate Treasuries still work. 9% in a 72% growth portfolio is intentionally thin: fixed income is held for drawdown buffering and the option to rebalance into equity weakness rather than for return. Would increase if real yields exceed 3% (making FI competitive on a return basis) or if the horizon shortens. Would reduce if the inflation regime persists and nominal duration stops hedging anything.",
        "view_summary": "Duration as recession ballast, sized for an aggressive growth portfolio. Classical 60/40 doctrine assumed Treasuries reliably hedged equity drawdowns; 2022 disproved that under inflationary regimes. But in deflationary or recessionary drawdowns, which remain the more common equity tail risk, intermediate Treasuries still work. 9% in a 72% growth portfolio is intentionally thin: fixed income is held for drawdown buffering and the option to rebalance into equity weakness rather than for return. Would increase if real yields exceed 3% (making FI competitive on a return basis) or if the horizon shortens. Would reduce if the inflation regime persists and nominal duration stops hedging anything."
    },
    "10": {
        "macro_view": "Inflation-hedged real-yield exposure, sized for a young investor's actual risk. At 27, the biggest fixed-income risk is not a market crash but an inflationary decade that silently destroys returns. TIPS hedge that risk directly through their CPI linkage. 6% is 40% of the fixed-income sleeve, heavier than typical institutional allocations (usually 20-30%), because the horizon is long enough for real-return preservation to dominate nominal. Post-2022 experience also reinforced that nominal Treasuries do not always hedge stocks the way 60/40 doctrine claimed; TIPS at least hedge inflation reliably. Would increase if real yields rise above 2.5%; would reduce if the horizon shortens or if confidence grows that disinflation will persist.",
        "view_summary": "Inflation-hedged real-yield exposure, sized for a young investor's actual risk. At 27, the biggest fixed-income risk is not a market crash but an inflationary decade that silently destroys returns. TIPS hedge that risk directly through their CPI linkage. 6% is 40% of the fixed-income sleeve, heavier than typical institutional allocations (usually 20-30%), because the horizon is long enough for real-return preservation to dominate nominal. Post-2022 experience also reinforced that nominal Treasuries do not always hedge stocks the way 60/40 doctrine claimed; TIPS at least hedge inflation reliably. Would increase if real yields rise above 2.5%; would reduce if the horizon shortens or if confidence grows that disinflation will persist."
    },
    "11": {
        "macro_view": "An inflation-correlated diversifier, with risk drivers unlike equity's or duration's. Public REITs and commodities are not perfect substitutes for the private real estate and natural resource exposure endowments hold, but at $10k they are the only honest implementation. 10% is large enough to move the portfolio's behavior in inflationary regimes, which 2-3% would not. It is not so large that REIT and commodity volatility (both can have 30%+ drawdowns) overwhelms the equity sleeves. Would increase if access to private real estate opens or if commodities enter sustained backwardation; would reduce in deflationary regimes where these assets stop earning their diversification benefit.",
        "view_summary": "An inflation-correlated diversifier, with risk drivers unlike equity's or duration's. Public REITs and commodities are not perfect substitutes for the private real estate and natural resource exposure endowments hold, but at $10k they are the only honest implementation. 10% is large enough to move the portfolio's behavior in inflationary regimes, which 2-3% would not. It is not so large that REIT and commodity volatility (both can have 30%+ drawdowns) overwhelms the equity sleeves. Would increase if access to private real estate opens or if commodities enter sustained backwardation; would reduce in deflationary regimes where these assets stop earning their diversification benefit."
    },
    "12": {
        "macro_view": "Operational liquidity, not strategic dry powder. At 27 with a 30+ year horizon, holding meaningful cash is a performance drag. Every 1% of cash at long-run equity returns of ~7% real costs ~$2.4k in terminal wealth per $10k of base capital over 30 years. 3% handles rebalancing friction (funding tax-inefficient sleeves without forced sales), small drawdowns without selling at the bottom, and occasional opportunistic deployment. SPAXX earns roughly the Treasury bill rate less its fee, so the drag is muted; the Macro page shows the live rate. Would increase closer to retirement or with shorter-duration liabilities; would reduce toward 1-2% if cash yields collapse below 2%.",
        "view_summary": "Operational liquidity, not strategic dry powder. At 27 with a 30+ year horizon, holding meaningful cash is a performance drag. Every 1% of cash at long-run equity returns of ~7% real costs ~$2.4k in terminal wealth per $10k of base capital over 30 years. 3% handles rebalancing friction (funding tax-inefficient sleeves without forced sales), small drawdowns without selling at the bottom, and occasional opportunistic deployment. SPAXX earns roughly the Treasury bill rate less its fee, so the drag is muted; the Macro page shows the live rate. Would increase closer to retirement or with shorter-duration liabilities; would reduce toward 1-2% if cash yields collapse below 2%.",
        "invalidation_conditions": "Operational liquidity thesis never invalidated: size adjusts, but a zero-cash policy is never appropriate in a taxable rebalancing portfolio."
    },
    "13": {
        "macro_view": "VOO delivers S&P 500 exposure at 0.03% with the best tax efficiency of any large-cap passive fund. The benchmark is SPY, used for attribution because it is the institutional standard. But SPY's unit investment trust structure prevents internal dividend reinvestment, creating cash drag and incremental tax events that accumulate over decades. Vanguard's ETF share class structure historically produces fewer capital gains distributions. The difference between VOO and SPY compounds over time; at a 30-year horizon, three times the fee is not worth paying for intraday liquidity the portfolio does not need.",
        "view_summary": "VOO delivers S&P 500 exposure at 0.03% with the best tax efficiency of any large-cap passive fund. The benchmark is SPY, used for attribution because it is the institutional standard. But SPY's unit investment trust structure prevents internal dividend reinvestment, creating cash drag and incremental tax events that accumulate over decades. Vanguard's ETF share class structure historically produces fewer capital gains distributions. The difference between VOO and SPY compounds over time; at a 30-year horizon, three times the fee is not worth paying for intraday liquidity the portfolio does not need.",
        "vehicle_rationale": "VOO delivers S&P 500 exposure at 0.03% with the best tax efficiency of any large-cap passive fund. The benchmark is SPY, used for attribution because it is the institutional standard. But SPY's unit investment trust structure prevents internal dividend reinvestment, creating cash drag and incremental tax events that accumulate over decades. Vanguard's ETF share class structure historically produces fewer capital gains distributions. The difference between VOO and SPY compounds over time; at a 30-year horizon, three times the fee is not worth paying for intraday liquidity the portfolio does not need."
    },
    "14": {
        "macro_view": "SPHQ over QUAL was a deliberate methodology choice rooted in accounting quality. QUAL screens on ROE, earnings variability, and debt-to-equity. SPHQ adds an accruals ratio screen, which filters out companies with aggressive accounting. High accruals relative to assets predict earnings reversals, as documented in Sloan (1996) and widely replicated since. CFA training reinforced this: accruals manipulation is real and persistent, and a quality screen that ignores it is incomplete. The tradeoff is smaller AUM ($6B vs QUAL's $40B), acceptable given SPHQ is not at closure-risk scale. Benchmarking against QUAL lets attribution show over time whether the accruals screen added or cost value.",
        "view_summary": "SPHQ over QUAL was a deliberate methodology choice rooted in accounting quality. QUAL screens on ROE, earnings variability, and debt-to-equity. SPHQ adds an accruals ratio screen, which filters out companies with aggressive accounting. High accruals relative to assets predict earnings reversals, as documented in Sloan (1996) and widely replicated since. CFA training reinforced this: accruals manipulation is real and persistent, and a quality screen that ignores it is incomplete. The tradeoff is smaller AUM ($6B vs QUAL's $40B), acceptable given SPHQ is not at closure-risk scale. Benchmarking against QUAL lets attribution show over time whether the accruals screen added or cost value.",
        "vehicle_rationale": "SPHQ over QUAL was a deliberate methodology choice rooted in accounting quality. QUAL screens on ROE, earnings variability, and debt-to-equity. SPHQ adds an accruals ratio screen, which filters out companies with aggressive accounting. High accruals relative to assets predict earnings reversals, as documented in Sloan (1996) and widely replicated since. CFA training reinforced this: accruals manipulation is real and persistent, and a quality screen that ignores it is incomplete. The tradeoff is smaller AUM ($6B vs QUAL's $40B), acceptable given SPHQ is not at closure-risk scale. Benchmarking against QUAL lets attribution show over time whether the accruals screen added or cost value."
    },
    "15": {
        "macro_view": "VTV captures the value factor through CRSP's multi-metric methodology (P/B, P/E, P/S, P/CF, and dividend yield) rather than Russell's P/B-heavy single metric used in IWD, the benchmark. Multi-metric is academically superior: relying solely on P/B overweights asset-heavy industries and underweights intangible-rich businesses where book value poorly proxies intrinsic value. VTV also costs 0.04% vs IWD's 0.19%. The holding deliberately differs from the benchmark on methodology.",
        "view_summary": "VTV captures the value factor through CRSP's multi-metric methodology (P/B, P/E, P/S, P/CF, and dividend yield) rather than Russell's P/B-heavy single metric used in IWD, the benchmark. Multi-metric is academically superior: relying solely on P/B overweights asset-heavy industries and underweights intangible-rich businesses where book value poorly proxies intrinsic value. VTV also costs 0.04% vs IWD's 0.19%. The holding deliberately differs from the benchmark on methodology.",
        "vehicle_rationale": "VTV captures the value factor through CRSP's multi-metric methodology (P/B, P/E, P/S, P/CF, and dividend yield) rather than Russell's P/B-heavy single metric used in IWD, the benchmark. Multi-metric is academically superior: relying solely on P/B overweights asset-heavy industries and underweights intangible-rich businesses where book value poorly proxies intrinsic value. VTV also costs 0.04% vs IWD's 0.19%. The holding deliberately differs from the benchmark on methodology."
    },
    "16": {
        "macro_view": "AVUV is the highest-conviction factor pick in the portfolio. Avantis (founded by former DFA researchers) targets the size, value, and profitability factors simultaneously. Empirically, the size premium is concentrated almost entirely in profitable small-value firms; unprofitable small caps drag index returns and explain why naive small-cap exposure has looked weak for 15 years. The 0.25% ER is the highest in the portfolio but buys factor exposure. Current large-cap valuations structurally improve the relative opportunity in cheap, profitable small companies. Attribution is tracked against IWM to test whether the factor tilt earns its fee over time.",
        "view_summary": "AVUV is the highest-conviction factor pick in the portfolio. Avantis (founded by former DFA researchers) targets the size, value, and profitability factors simultaneously. Empirically, the size premium is concentrated almost entirely in profitable small-value firms; unprofitable small caps drag index returns and explain why naive small-cap exposure has looked weak for 15 years. The 0.25% ER is the highest in the portfolio but buys factor exposure. Current large-cap valuations structurally improve the relative opportunity in cheap, profitable small companies. Attribution is tracked against IWM to test whether the factor tilt earns its fee over time.",
        "vehicle_rationale": "AVUV is the highest-conviction factor pick in the portfolio. Avantis (founded by former DFA researchers) targets the size, value, and profitability factors simultaneously. Empirically, the size premium is concentrated almost entirely in profitable small-value firms; unprofitable small caps drag index returns and explain why naive small-cap exposure has looked weak for 15 years. The 0.25% ER is the highest in the portfolio but buys factor exposure. Current large-cap valuations structurally improve the relative opportunity in cheap, profitable small companies. Attribution is tracked against IWM to test whether the factor tilt earns its fee over time."
    },
    "17": {
        "macro_view": "The cap-weighted developed ex-US market, held for the reason any core position is held: it is the region without a view. VEA is the cheapest instrument for the exposure. IEFA is held as a substitute in the same sleeve, tracking the same developed universe.",
        "view_summary": "The cap-weighted developed ex-US market, held for the reason any core position is held: it is the region without a view. VEA is the cheapest instrument for the exposure. IEFA is held as a substitute in the same sleeve, tracking the same developed universe.",
        "vehicle_rationale": "The cap-weighted developed ex-US market, held for the reason any core position is held: it is the region without a view. VEA is the cheapest instrument for the exposure. IEFA is held as a substitute in the same sleeve, tracking the same developed universe."
    },
    "18": {
        "macro_view": "IEMG is the holding because EEM costs 0.70% for identical exposure: seven times more expensive, and the largest benchmark-to-holding fee gap in the portfolio. IEMG at 0.09% tracks the same MSCI Emerging Markets index with the same ~27% China weight. China inclusion was deliberate. The SAA rationale flags governance risk as a watch item but not yet a reason to exit: China trades at ~10x P/E, and the EM valuation thesis meaningfully includes Chinese equities. Excluding China via EMXC would be a larger active bet than appropriate at current prices. Would revisit if ADR delisting risk materializes legislatively or if another sector-level government intervention occurs.",
        "view_summary": "IEMG is the holding because EEM costs 0.70% for identical exposure: seven times more expensive, and the largest benchmark-to-holding fee gap in the portfolio. IEMG at 0.09% tracks the same MSCI Emerging Markets index with the same ~27% China weight. China inclusion was deliberate. The SAA rationale flags governance risk as a watch item but not yet a reason to exit: China trades at ~10x P/E, and the EM valuation thesis meaningfully includes Chinese equities. Excluding China via EMXC would be a larger active bet than appropriate at current prices. Would revisit if ADR delisting risk materializes legislatively or if another sector-level government intervention occurs.",
        "vehicle_rationale": "IEMG is the holding because EEM costs 0.70% for identical exposure: seven times more expensive, and the largest benchmark-to-holding fee gap in the portfolio. IEMG at 0.09% tracks the same MSCI Emerging Markets index with the same ~27% China weight. China inclusion was deliberate. The SAA rationale flags governance risk as a watch item but not yet a reason to exit: China trades at ~10x P/E, and the EM valuation thesis meaningfully includes Chinese equities. Excluding China via EMXC would be a larger active bet than appropriate at current prices. Would revisit if ADR delisting risk materializes legislatively or if another sector-level government intervention occurs."
    },
    "19": {
        "macro_view": "VGIT delivers intermediate-term US Treasury exposure at 0.04% versus IEF's 0.15%. Duration is modestly shorter (~5.5 years vs IEF's ~7.5 years), appropriate for a 9% sleeve inside a 72% growth portfolio. Critically, Treasury interest income is exempt from state and local taxes: a real after-tax advantage in a high-income-tax jurisdiction like DC over investment-grade corporate bond funds with similar yield. Cost minimization is the dominant selection criterion for a sleeve that exists for drawdown buffering and rebalancing optionality, not return.",
        "view_summary": "VGIT delivers intermediate-term US Treasury exposure at 0.04% versus IEF's 0.15%. Duration is modestly shorter (~5.5 years vs IEF's ~7.5 years), appropriate for a 9% sleeve inside a 72% growth portfolio. Critically, Treasury interest income is exempt from state and local taxes: a real after-tax advantage in a high-income-tax jurisdiction like DC over investment-grade corporate bond funds with similar yield. Cost minimization is the dominant selection criterion for a sleeve that exists for drawdown buffering and rebalancing optionality, not return.",
        "vehicle_rationale": "VGIT delivers intermediate-term US Treasury exposure at 0.04% versus IEF's 0.15%. Duration is modestly shorter (~5.5 years vs IEF's ~7.5 years), appropriate for a 9% sleeve inside a 72% growth portfolio. Critically, Treasury interest income is exempt from state and local taxes: a real after-tax advantage in a high-income-tax jurisdiction like DC over investment-grade corporate bond funds with similar yield. Cost minimization is the dominant selection criterion for a sleeve that exists for drawdown buffering and rebalancing optionality, not return."
    },
    "21": {
        "macro_view": "PDBC is the only broad commodity ETF worth owning in a taxable account because it avoids issuing a K-1 tax form. Nearly all commodity futures funds are organized as partnerships and issue K-1s annually, which complicate filing, often arrive late, and can trigger estimated tax requirements. PDBC uses a C-corporation structure instead, eliminating K-1 at the cost of a higher ER (0.59%). For a 5% position in a taxable account, tax simplicity is worth materially more than the fee difference versus K-1-issuing alternatives. DJP (the benchmark) is an exchange-traded note with counterparty risk, used for attribution only and never as a holding.",
        "view_summary": "PDBC is the only broad commodity ETF worth owning in a taxable account because it avoids issuing a K-1 tax form. Nearly all commodity futures funds are organized as partnerships and issue K-1s annually, which complicate filing, often arrive late, and can trigger estimated tax requirements. PDBC uses a C-corporation structure instead, eliminating K-1 at the cost of a higher ER (0.59%). For a 5% position in a taxable account, tax simplicity is worth materially more than the fee difference versus K-1-issuing alternatives. DJP (the benchmark) is an exchange-traded note with counterparty risk, used for attribution only and never as a holding.",
        "vehicle_rationale": "PDBC is the only broad commodity ETF worth owning in a taxable account because it avoids issuing a K-1 tax form. Nearly all commodity futures funds are organized as partnerships and issue K-1s annually, which complicate filing, often arrive late, and can trigger estimated tax requirements. PDBC uses a C-corporation structure instead, eliminating K-1 at the cost of a higher ER (0.59%). For a 5% position in a taxable account, tax simplicity is worth materially more than the fee difference versus K-1-issuing alternatives. DJP (the benchmark) is an exchange-traded note with counterparty risk, used for attribution only and never as a holding."
    },
    "22": {
        "macro_view": "VNQ is the standard for US REIT exposure: $35B AUM, 0.12% ER, and broad diversification across property types. Primary risk accepted knowingly: REIT distributions are predominantly non-qualified income taxed at ordinary rates. In a perfect construction this sleeve would sit in a tax-advantaged account; with only a taxable account available, the drag is accepted. The real assets diversification benefit justifies carrying the tax friction. Would revisit if tax-advantaged space becomes available.",
        "view_summary": "VNQ is the standard for US REIT exposure: $35B AUM, 0.12% ER, and broad diversification across property types. Primary risk accepted knowingly: REIT distributions are predominantly non-qualified income taxed at ordinary rates. In a perfect construction this sleeve would sit in a tax-advantaged account; with only a taxable account available, the drag is accepted. The real assets diversification benefit justifies carrying the tax friction. Would revisit if tax-advantaged space becomes available.",
        "vehicle_rationale": "VNQ is the standard for US REIT exposure: $35B AUM, 0.12% ER, and broad diversification across property types. Primary risk accepted knowingly: REIT distributions are predominantly non-qualified income taxed at ordinary rates. In a perfect construction this sleeve would sit in a tax-advantaged account; with only a taxable account available, the drag is accepted. The real assets diversification benefit justifies carrying the tax friction. Would revisit if tax-advantaged space becomes available."
    }
}


def main() -> int:
    conn = sqlite3.connect(DEMO_DB)
    changed = 0
    try:
        with conn:
            for thesis_id, cells in NEW.items():
                for col, text in cells.items():
                    row = conn.execute(f"SELECT {col} FROM theses WHERE thesis_id = ?",
                                       (thesis_id,)).fetchone()
                    if row is None:
                        raise SystemExit(f"ABORT: thesis {thesis_id} is missing")
                    if row[0] == text:
                        continue
                    n = conn.execute(UPDATES[col], (text, thesis_id, row[0])).rowcount
                    if n != 1:
                        raise SystemExit(f"ABORT: thesis {thesis_id}.{col} changed {n} rows")
                    changed += 1
    finally:
        conn.close()
    print(f"{DEMO_DB.name}: {changed} thesis cell(s) changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
